app = "aamuzbot"
primary_region = "ams" # Amsterdam

[build]
  dockerfile = "Dockerfile"

[env]
  BOT_ENV = "prod"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/webhook"

[metrics]
  port = 8000
  path = "/metrics" 